"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const base:React.CSSProperties={background:"linear-gradient(135deg,#06101f 0%,#081a32 52%,#06101f 100%)",color:"#f4f8ff",minHeight:"100vh",fontFamily:"Inter,system-ui,sans-serif"};
const card:React.CSSProperties={background:"rgba(10,24,43,.88)",border:"1px solid rgba(82,168,255,.14)",borderRadius:20,padding:22,boxShadow:"0 18px 55px rgba(0,0,0,.18)"};
const input:React.CSSProperties={width:"100%",background:"#071525",color:"#edf6ff",border:"1px solid rgba(148,163,184,.18)",borderRadius:11,padding:"12px 13px",outline:"none"};
const button:React.CSSProperties={background:"linear-gradient(135deg,#1984ff,#1261df)",color:"#fff",border:0,borderRadius:11,padding:"11px 15px",fontWeight:800,cursor:"pointer"};
export default function AdminSettings(){
 const [theme,setTheme]=useState("dark"),[language,setLanguage]=useState("fr"),[currency,setCurrency]=useState("XOF"),[adminId,setAdminId]=useState(""),[role,setRole]=useState("admin"),[reason,setReason]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{setTheme(localStorage.getItem("safepay-admin-theme")||"dark");setLanguage(localStorage.getItem("safepay-admin-language")||"fr");setCurrency(localStorage.getItem("safepay-admin-currency")||"XOF")},[]);
 function savePref(key:string,value:string){localStorage.setItem(key,value);setMessage("Préférence enregistrée.");if(key.endsWith("theme")){document.documentElement.dataset.adminTheme=value;document.documentElement.dataset.adminThemeResolved=value}}
 async function addAdmin(){if(!adminId)return;setBusy(true);setMessage("");const s=createClient();const gate=await s.rpc("is_admin");if(gate.error||!gate.data){setMessage("Accès administrateur requis.");setBusy(false);return;}const r=await s.rpc("admin_manage_admin_users",{p_target_user_id:adminId,p_action:"add",p_role:role,p_reason:reason||"Ajout depuis Paramètres Admin"});setMessage(r.error?r.error.message:"Administrateur ajouté dans SafePay.");setBusy(false);if(!r.error){setAdminId("");setReason("")}}
 return <main style={base}><div style={{maxWidth:1180,margin:"0 auto",padding:"28px 22px 48px"}}><a href="/admin" style={{color:"#7fc0ff",textDecoration:"none",fontSize:13}}>← Retour au Dashboard</a><header style={{margin:"24px 0 20px"}}><div style={{color:"#59a9ff",fontSize:11,fontWeight:900,letterSpacing:".18em"}}>CONFIGURATION • PRÉFÉRENCES</div><h1 style={{fontSize:36,margin:"8px 0"}}>Paramètres SafePay Admin</h1><p style={{color:"#8fa6bf",maxWidth:720}}>Toutes les préférences d'interface sont regroupées ici. Les règles financières restent pilotées par le backend.</p></header>
 <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:16}}>
  <section style={card}><div style={{fontSize:26}}>◐</div><h2>Thème</h2><p style={{color:"#8fa6bf",fontSize:13}}>Choisis une interface sombre puissante, claire ou synchronisée avec le système.</p><select value={theme} onChange={e=>{setTheme(e.target.value);savePref("safepay-admin-theme",e.target.value)}} style={{...input,marginTop:12}}><option value="dark">Sombre — recommandé</option><option value="light">Clair</option><option value="system">Système</option></select></section>
  <section style={card}><div style={{fontSize:26}}>文</div><h2>Langue</h2><p style={{color:"#8fa6bf",fontSize:13}}>Langue d'affichage du tableau de bord administrateur.</p><select value={language} onChange={e=>{setLanguage(e.target.value);savePref("safepay-admin-language",e.target.value)}} style={{...input,marginTop:12}}><option value="fr">Français</option><option value="en">English</option></select></section>
  <section style={card}><div style={{fontSize:26}}>₣</div><h2>Devise</h2><p style={{color:"#8fa6bf",fontSize:13}}>Devise utilisée pour les indicateurs et analyses financières.</p><select value={currency} onChange={e=>{setCurrency(e.target.value);savePref("safepay-admin-currency",e.target.value)}} style={{...input,marginTop:12}}><option value="XOF">XOF — Franc CFA</option><option value="EUR">EUR — Euro</option><option value="USD">USD — Dollar US</option></select></section>
  <section style={{...card,gridColumn:"1 / -1"}}><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",flexWrap:"wrap"}}><div><div style={{color:"#59a9ff",fontSize:10,fontWeight:900,letterSpacing:".12em"}}>ACCÈS ADMINISTRATEURS</div><h2>Gestion des administrateurs</h2><p style={{color:"#8fa6bf",fontSize:13}}>Ajoute un utilisateur SafePay existant à <b>admin_users</b>. Chaque action est contrôlée et journalisée.</p></div><span style={{padding:"8px 11px",borderRadius:20,background:"rgba(22,119,255,.12)",color:"#8fc8ff",fontSize:12}}>Supabase • Backend source of truth</span></div><div style={{display:"grid",gridTemplateColumns:"2fr 1fr 2fr auto",gap:10,marginTop:18}}><input value={adminId} onChange={e=>setAdminId(e.target.value)} placeholder="UUID du profil existant" style={input}/><select value={role} onChange={e=>setRole(e.target.value)} style={input}><option value="admin">Admin</option><option value="super_admin">Super Admin</option><option value="support">Support</option></select><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motif d'audit" style={input}/><button disabled={busy||!adminId} onClick={addAdmin} style={{...button,opacity:busy||!adminId?0.5:1}}>{busy?"Ajout…":"Ajouter"}</button></div>{message&&<p style={{marginTop:14,color:"#7fe0ac"}}>{message}</p>}</section>
  <section style={{...card,gridColumn:"1 / -1"}}><div style={{color:"#59a9ff",fontSize:10,fontWeight:900,letterSpacing:".12em"}}>FINANCE</div><h2>Gestion financière</h2><p style={{color:"#8fa6bf",fontSize:13}}>Commissions, payeur des frais, providers, Collection, Payout et simulateur sont gérés dans l'espace Finance dédié.</p><a href="/admin/financial" style={{...button,display:"inline-block",textDecoration:"none",marginTop:8}}>Ouvrir Finance & Commissions →</a></section>
 </div></div></main>;
}
