"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Summary={available:number;pending:number;withdrawn:number;reversed:number;total:number;currency:string};
type Withdrawal={id:string;amount:number;currency:string;provider:string;destination_phone:string;provider_reference:string|null;status:string;created_at:string;updated_at:string;completed_at:string|null;failure_reason:string|null};
const money=(n:number,c="XOF")=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:c.trim(),maximumFractionDigits:0}).format(Number(n));
const input:React.CSSProperties={width:"100%",background:"#071222",color:"#e8f1ff",border:"1px solid rgba(148,163,184,.16)",borderRadius:10,padding:"11px 12px",outline:"none"};
const card:React.CSSProperties={background:"#0a1424",border:"1px solid rgba(148,163,184,.13)",borderRadius:18,padding:20};
const button:React.CSSProperties={background:"#1677ff",color:"#fff",border:0,borderRadius:10,padding:"11px 15px",fontWeight:800,cursor:"pointer"};
export default function RevenuePage(){
 const [summary,setSummary]=useState<Summary|null>(null),[rows,setRows]=useState<Withdrawal[]>([]),[amount,setAmount]=useState(""),[provider,setProvider]=useState("T-Money"),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const s=createClient();const [{data:sum,error:se},{data:ws,error:we}]=await Promise.all([s.rpc("admin_revenue_summary"),s.rpc("admin_revenue_withdrawals",{p_limit:50})]);if(se)setMessage(se.message);else setSummary(sum as Summary);if(we)setMessage(we.message);else setRows((ws??[]) as Withdrawal[])};
 useEffect(()=>{load()},[]);
 async function withdraw(){const n=Number(amount);if(!Number.isFinite(n)||n<=0){setMessage("Montant invalide.");return}if(!/^\\+?[0-9]{8,15}$/.test(phone.replace(/\\s/g,""))){setMessage("Numéro bénéficiaire invalide.");return}if(!summary||n>Number(summary.available)){setMessage("Le montant dépasse le revenu disponible.");return}if(!confirm(`Retirer ${money(n)} vers ${phone} via ${provider} ?`))return;setBusy(true);setMessage("");try{const {data,error}=await createClient().functions.invoke("cinetpay-revenue-withdraw",{body:{amount:n,currency:"XOF",provider,phone,idempotency_key:crypto.randomUUID()}});if(error)throw error;if(data?.error)throw new Error(data.message||data.error);setMessage(`Retrait créé : ${data.withdrawal_id}. Statut : ${data.status}.`);setAmount("");await load()}catch(e){setMessage(e instanceof Error?e.message:"Retrait impossible.")}finally{setBusy(false)}}
 return <main style={{background:"#050b16",color:"#f1f6ff",minHeight:"100vh",fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1200,margin:"0 auto",padding:28}}>
 <div style={{display:"flex",gap:16,flexWrap:"wrap",marginBottom:20}}><a href="/admin" style={{color:"#72b4ff",textDecoration:"none"}}>← Dashboard Admin</a><a href="/admin/financial" style={{color:"#72b4ff",textDecoration:"none"}}>Finance / Commissions</a></div>
 <header style={{marginBottom:24}}><small style={{color:"#6295cc",letterSpacing:".15em",fontWeight:800}}>SAFEPAY REVENUE</small><h1 style={{fontSize:34,margin:"8px 0"}}>Revenus & retraits</h1><p style={{color:"#8094aa"}}>Les commissions confirmées deviennent des revenus SafePay traçables. Les retraits sont exécutés côté serveur via CinetPay.</p></header>
 <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginBottom:16}}>{[["Disponible",summary?.available??0],["En attente",summary?.pending??0],["Déjà retiré",summary?.withdrawn??0],["Total historique",summary?.total??0]].map(([l,v])=><section key={String(l)} style={card}><div style={{color:"#8094aa",fontSize:13}}>{l}</div><strong style={{display:"block",fontSize:23,marginTop:8}}>{money(Number(v))}</strong></section>)}</div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1.4fr",gap:16,alignItems:"start"}}>
 <section style={card}><h2 style={{marginTop:0}}>Retirer mes revenus</h2><p style={{color:"#8094aa",fontSize:13}}>Le montant est réservé avant l'appel CinetPay. En cas d'échec, il revient automatiquement dans le revenu disponible.</p><label>Montant (XOF)<input style={input} inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,""))} placeholder="10000"/></label><label style={{display:"block",marginTop:12}}>Provider<select style={input} value={provider} onChange={e=>setProvider(e.target.value)}><option>T-Money</option><option>Moov Money</option></select></label><label style={{display:"block",marginTop:12}}>Numéro bénéficiaire<input style={input} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+228..." autoComplete="tel"/></label><button style={{...button,marginTop:14,width:"100%"}} disabled={busy||!summary||Number(amount)<=0} onClick={withdraw}>{busy?"Traitement…":"Demander le retrait"}</button><div style={{marginTop:14,padding:12,borderRadius:10,background:"#071222",fontSize:12,color:"#8ea2b8"}}>Les clés CinetPay ne sont jamais envoyées au navigateur. La demande appelle uniquement l'Edge Function sécurisée.</div></section>
 <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><h2 style={{margin:"0 0 5px"}}>Historique des retraits</h2><p style={{margin:0,color:"#8094aa",fontSize:13}}>Source : Supabase, pas de données locales.</p></div><button style={{...button,background:"#24344a"}} onClick={load}>Actualiser</button></div><div style={{overflowX:"auto",marginTop:16}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Date","Montant","Provider","Destination","Statut","Référence"].map(x=><th key={x} style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid rgba(148,163,184,.12)",color:"#8094aa"}}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td style={{padding:"12px 8px"}}>{new Date(r.created_at).toLocaleString("fr-FR")}</td><td style={{padding:"12px 8px",fontWeight:800}}>{money(r.amount,r.currency)}</td><td style={{padding:"12px 8px"}}>{r.provider}</td><td style={{padding:"12px 8px"}}>{r.destination_phone}</td><td style={{padding:"12px 8px"}}><span style={{padding:"5px 8px",borderRadius:8,background:r.status==="successful"?"#0d7a53":r.status==="failed"?"#7a2530":"#24344a"}}>{r.status}</span></td><td style={{padding:"12px 8px",fontFamily:"monospace"}}>{r.provider_reference||"—"}</td></tr>):<tr><td colSpan={6} style={{padding:24,textAlign:"center",color:"#8094aa"}}>Aucun retrait pour le moment.</td></tr>}</tbody></table></div></section></div>{message&&<div style={{...card,marginTop:16,color:"#b9d5ff"}}>{message}</div>}</div></main>;
}
