"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Point={date:string;transaction_volume?:number;revenue?:number;safepay_revenue?:number;traffic?:number;transactions?:number};
type Summary={available:number;pending:number;withdrawn:number;reversed:number;total:number;currency:string};
type Withdrawal={id:string;amount:number;currency:string;provider:string;destination_phone:string;provider_reference:string|null;status:string;created_at:string;updated_at:string;completed_at:string|null;failure_reason:string|null};
const money=(n:number,c="XOF")=>{try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency:c.trim(),maximumFractionDigits:0}).format(Number(n))}catch{return `${Number(n).toLocaleString("fr-FR")} ${c}`}};
const card:React.CSSProperties={background:"rgba(10,24,43,.9)",border:"1px solid rgba(82,168,255,.14)",borderRadius:20,padding:20,boxShadow:"0 18px 55px rgba(0,0,0,.18)"};
const input:React.CSSProperties={width:"100%",background:"#071525",color:"#edf6ff",border:"1px solid rgba(148,163,184,.18)",borderRadius:11,padding:"11px 12px",outline:"none"};
const button:React.CSSProperties={background:"linear-gradient(135deg,#1984ff,#1261df)",color:"#fff",border:0,borderRadius:11,padding:"10px 14px",fontWeight:800,cursor:"pointer"};
function startOfMonday(d:Date){const x=new Date(d);x.setHours(0,0,0,0);const day=x.getDay();const diff=day===0?-6:1-day;x.setDate(x.getDate()+diff);return x}
function iso(d:Date){return d.toISOString().slice(0,10)}
export default function RevenuePage(){
 const [summary,setSummary]=useState<Summary|null>(null),[rows,setRows]=useState<Withdrawal[]>([]),[points,setPoints]=useState<Point[]>([]),[amount,setAmount]=useState(""),[provider,setProvider]=useState("T-Money"),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[start,setStart]=useState(()=>iso(startOfMonday(new Date()))),[end,setEnd]=useState(()=>{const d=startOfMonday(new Date());d.setDate(d.getDate()+6);return iso(d)}),[currency,setCurrency]=useState("XOF");
 const load=async()=>{const s=createClient();const [{data:sum,error:se},{data:ws,error:we},{data:ts,error:te}]=await Promise.all([s.rpc("admin_revenue_summary"),s.rpc("admin_revenue_withdrawals",{p_limit:50}),s.rpc("admin_analytics_timeseries",{p_days:365})]);if(se)setMessage(se.message);else setSummary(sum as Summary);if(we)setMessage(we.message);else setRows((ws??[]) as Withdrawal[]);if(te)setMessage(te.message);else setPoints((ts??[]) as Point[])};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>points.filter(p=>{const d=String(p.date).slice(0,10);return d>=start&&d<=end}),[points,start,end]);
 const revenueTotal=filtered.reduce((a,p)=>a+Number(p.safepay_revenue??p.revenue??0),0); const trafficTotal=filtered.reduce((a,p)=>a+Number(p.traffic??p.transactions??p.transaction_volume??0),0);
 function thisWeek(){const s=startOfMonday(new Date()),e=new Date(s);e.setDate(e.getDate()+6);setStart(iso(s));setEnd(iso(e))}
 function previousWeek(){const e=startOfMonday(new Date());e.setDate(e.getDate()-1);const s=startOfMonday(e);setStart(iso(s));setEnd(iso(e))}
 async function withdraw(){const n=Number(amount);if(!Number.isFinite(n)||n<=0){setMessage("Montant invalide.");return}const clean=phone.replace(/\s/g,"");if(!/^\+?[0-9]{8,15}$/.test(clean)){setMessage("Numéro bénéficiaire invalide.");return}if(!summary||n>Number(summary.available)){setMessage("Le montant dépasse le revenu disponible.");return}if(!confirm(`Retirer ${money(n)} vers ${phone} via ${provider} ?`))return;setBusy(true);setMessage("");try{const {data,error}=await createClient().functions.invoke("cinetpay-revenue-withdraw",{body:{amount:n,currency:"XOF",provider,phone,idempotency_key:crypto.randomUUID()}});if(error)throw error;if(data?.error)throw new Error(data.message||data.error);setMessage(`Retrait créé : ${data.withdrawal_id}. Statut : ${data.status}.`);setAmount("");await load()}catch(e){setMessage(e instanceof Error?e.message:"Retrait impossible.")}finally{setBusy(false)}}
 const maxRevenue=Math.max(1,...filtered.map(p=>Number(p.safepay_revenue??p.revenue??0)));const maxTraffic=Math.max(1,...filtered.map(p=>Number(p.traffic??p.transactions??p.transaction_volume??0)));
 return <main style={{background:"linear-gradient(135deg,#06101f 0%,#081a32 55%,#06101f 100%)",color:"#f4f8ff",minHeight:"100vh",fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1280,margin:"0 auto",padding:"28px 22px 50px"}}>
 <div style={{display:"flex",gap:16,flexWrap:"wrap",marginBottom:22}}><a href="/admin" style={{color:"#7fc0ff",textDecoration:"none"}}>← Dashboard Admin</a><a href="/admin/financial" style={{color:"#7fc0ff",textDecoration:"none"}}>Finance / Commissions</a></div>
 <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",flexWrap:"wrap",marginBottom:20}}><div><div style={{color:"#59a9ff",fontSize:11,fontWeight:900,letterSpacing:".18em"}}>SAFEPAY • REVENUS</div><h1 style={{fontSize:38,margin:"7px 0"}}>Revenus & performance</h1><p style={{color:"#8fa6bf",maxWidth:720,margin:0}}>Une lecture claire de ce que SafePay gagne par commission et du trafic généré sur la période sélectionnée.</p></div><div style={{padding:"9px 12px",borderRadius:20,background:"rgba(22,119,255,.12)",color:"#9bcfff",fontSize:12}}>Période : {start} → {end}</div></header>
 <section style={{...card,marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"end",flexWrap:"wrap"}}><div><div style={{color:"#59a9ff",fontSize:10,fontWeight:900,letterSpacing:".12em"}}>CALENDRIER ANALYTIQUE</div><h2 style={{margin:"6px 0"}}>Choisir la période</h2><p style={{margin:0,color:"#8fa6bf",fontSize:12}}>Les semaines sont structurées du lundi au dimanche.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={{...button,background:"#14365e"}} onClick={thisWeek}>Cette semaine · Lun → Dim</button><button style={{...button,background:"#14365e"}} onClick={previousWeek}>Semaine précédente</button></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:10,marginTop:16,alignItems:"end"}}><label style={{fontSize:12,color:"#a8bad0"}}>Date de début<input type="date" value={start} onChange={e=>setStart(e.target.value)} style={input}/></label><label style={{fontSize:12,color:"#a8bad0"}}>Date de fin<input type="date" value={end} onChange={e=>setEnd(e.target.value)} style={input}/></label><button style={button} onClick={load}>Actualiser les données</button></div></section>
 <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginBottom:16}}>{[["Revenu disponible",summary?.available??0],["Revenu période",revenueTotal],["Trafic période",trafficTotal],["Total historique",summary?.total??0]].map(([l,v],i)=><section key={String(l)} style={card}><div style={{color:"#8fa6bf",fontSize:12}}>{l}</div><strong style={{display:"block",fontSize:24,marginTop:8}}>{i===2?Number(v).toLocaleString("fr-FR"):money(Number(v),currency)}</strong><small style={{display:"block",marginTop:5,color:"#59a9ff"}}>{i===1?"Commission SafePay":i===2?"Transactions / activité":"SafePay"}</small></section>)}</div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
  <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{color:"#59a9ff",fontSize:10,fontWeight:900}}>REVENUS</div><h2 style={{margin:"5px 0"}}>Ce que SafePay gagne</h2></div><strong style={{fontSize:18}}>{money(revenueTotal,currency)}</strong></div><div style={{height:250,display:"flex",alignItems:"end",gap:5,marginTop:18,borderBottom:"1px solid rgba(148,163,184,.12)",padding:"10px 0 0"}}>{filtered.length?filtered.map(p=>{const n=Number(p.safepay_revenue??p.revenue??0);return <div key={p.date} style={{flex:1,height:`${Math.max(4,n/maxRevenue*100)}%`,background:"linear-gradient(180deg,#52a8ff,#1261df)",borderRadius:"6px 6px 0 0",minWidth:4}} title={`${p.date} • ${money(n,currency)}`}/>):<div style={{color:"#8fa6bf",alignSelf:"center",width:"100%",textAlign:"center"}}>Aucune donnée sur cette période.</div>}</div><div style={{display:"flex",justifyContent:"space-between",color:"#71869e",fontSize:10,marginTop:8}}><span>{start}</span><span>{end}</span></div></section>
  <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{color:"#59a9ff",fontSize:10,fontWeight:900}}>TRAFIC</div><h2 style={{margin:"5px 0"}}>Activité SafePay</h2></div><strong style={{fontSize:18}}>{trafficTotal.toLocaleString("fr-FR")}</strong></div><div style={{height:250,display:"flex",alignItems:"end",gap:5,marginTop:18,borderBottom:"1px solid rgba(148,163,184,.12)",padding:"10px 0 0"}}>{filtered.length?filtered.map(p=>{const n=Number(p.traffic??p.transactions??p.transaction_volume??0);return <div key={p.date} style={{flex:1,height:`${Math.max(4,n/maxTraffic*100)}%`,background:"linear-gradient(180deg,#8cc9ff,#1677ff)",borderRadius:"6px 6px 0 0",minWidth:4}} title={`${p.date} • ${n.toLocaleString("fr-FR")} activités`}/>):<div style={{color:"#8fa6bf",alignSelf:"center",width:"100%",textAlign:"center"}}>Aucune donnée sur cette période.</div>}</div><div style={{display:"flex",justifyContent:"space-between",color:"#71869e",fontSize:10,marginTop:8}}><span>{start}</span><span>{end}</span></div></section>
 </div>
 <div style={{display:"grid",gridTemplateColumns:".8fr 1.2fr",gap:16,alignItems:"start"}}><section style={card}><div style={{color:"#59a9ff",fontSize:10,fontWeight:900}}>PAYOUT</div><h2>Retirer mes revenus</h2><p style={{color:"#8fa6bf",fontSize:13}}>Le montant est réservé avant l'appel CinetPay. En cas d'échec, il revient automatiquement dans le revenu disponible.</p><label>Montant (XOF)<input style={input} inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,""))} placeholder="10000"/></label><label style={{display:"block",marginTop:12}}>Provider<select style={input} value={provider} onChange={e=>setProvider(e.target.value)}><option>T-Money</option><option>Moov Money</option></select></label><label style={{display:"block",marginTop:12}}>Numéro bénéficiaire<input style={input} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+228..." autoComplete="tel"/></label><button style={{...button,marginTop:14,width:"100%"}} disabled={busy||!summary||Number(amount)<=0} onClick={withdraw}>{busy?"Traitement…":"Demander le retrait"}</button></section>
 <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{color:"#59a9ff",fontSize:10,fontWeight:900}}>HISTORIQUE</div><h2 style={{margin:"5px 0"}}>Retraits SafePay</h2></div><button style={{...button,background:"#14365e"}} onClick={load}>Actualiser</button></div><div style={{overflowX:"auto",marginTop:14}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Date","Montant","Provider","Destination","Statut","Référence"].map(x=><th key={x} style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid rgba(148,163,184,.12)",color:"#71869e"}}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td style={{padding:"11px 8px"}}>{new Date(r.created_at).toLocaleString("fr-FR")}</td><td style={{padding:"11px 8px",fontWeight:800}}>{money(r.amount,r.currency)}</td><td style={{padding:"11px 8px"}}>{r.provider}</td><td style={{padding:"11px 8px"}}>{r.destination_phone}</td><td style={{padding:"11px 8px"}}><span style={{padding:"5px 8px",borderRadius:8,background:r.status==="successful"?"#0d7a53":r.status==="failed"?"#7a2530":"#14365e"}}>{r.status}</span></td><td style={{padding:"11px 8px",fontFamily:"monospace"}}>{r.provider_reference||"—"}</td></tr>):<tr><td colSpan={6} style={{padding:24,textAlign:"center",color:"#71869e"}}>Aucun retrait pour le moment.</td></tr>}</tbody></table></div></section></div>
 {message&&<div style={{...card,marginTop:16,color:"#b9d5ff"}}>{message}</div>}
 </div></main>;
}
