"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function AdminAddOverlay(){
 const [active,setActive]=useState(false),[open,setOpen]=useState(false),[userId,setUserId]=useState(""),[role,setRole]=useState("admin"),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const check=()=>{const buttons=Array.from(document.querySelectorAll('.adm-sidebar nav button'));setActive(buttons.some((b)=>b.classList.contains('active')&&b.textContent?.includes('Administrateurs')))};check();const obs=new MutationObserver(check);obs.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});return()=>obs.disconnect()},[]);
 if(!active)return null;
 async function add(){if(!userId.trim())return;setBusy(true);setMessage("");const s=createClient();const gate=await s.rpc('is_admin');if(gate.error||!gate.data){setMessage('Accès administrateur requis.');setBusy(false);return;}const r=await s.rpc('admin_manage_admin_users',{p_target_user_id:userId.trim(),p_action:'add',p_role:role,p_reason:reason.trim()||'Ajout depuis Administrateurs'});if(r.error)setMessage(r.error.message);else{setMessage('Administrateur ajouté avec succès.');setUserId('');setReason('');setOpen(false)}setBusy(false)}
 return <><button onClick={()=>setOpen(true)} style={{position:'fixed',right:28,top:92,zIndex:60,background:'linear-gradient(135deg,#1984ff,#1261df)',color:'#fff',border:0,borderRadius:11,padding:'11px 15px',fontWeight:800,cursor:'pointer',boxShadow:'0 10px 30px rgba(0,0,0,.25)'}}>＋ Ajouter un administrateur</button>{open&&<div onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}} style={{position:'fixed',inset:0,zIndex:100,background:'rgba(2,8,18,.72)',display:'grid',placeItems:'center',padding:20}}><div style={{width:'min(520px,100%)',background:'#0b1a2d',color:'#f4f8ff',border:'1px solid rgba(82,168,255,.2)',borderRadius:18,padding:22}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><small style={{color:'#59a9ff',fontWeight:900,letterSpacing:'.12em'}}>SÉCURITÉ & ACCÈS</small><h2 style={{margin:'6px 0'}}>Ajouter un administrateur</h2></div><button onClick={()=>setOpen(false)} style={{background:'transparent',color:'#fff',border:0,fontSize:22}}>×</button></div><p style={{color:'#8fa6bf',fontSize:13}}>L'utilisateur doit déjà exister dans SafePay. Son accès sera enregistré dans <b>admin_users</b> et journalisé.</p><input value={userId} onChange={e=>setUserId(e.target.value)} placeholder="UUID de l'utilisateur SafePay" style={input}/><select value={role} onChange={e=>setRole(e.target.value)} style={{...input,marginTop:10}}><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motif d'audit (optionnel)" style={{...input,minHeight:90,marginTop:10}}/><div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:12}}><button onClick={()=>setOpen(false)} style={secondary}>Annuler</button><button onClick={add} disabled={busy||!userId.trim()} style={primary}>{busy?'Ajout…':'Ajouter'}</button></div>{message&&<p style={{color:message.includes('succès')?'#7fe0ac':'#ff9c9c'}}>{message}</p>}</div></div>}</>;
}
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#071525',color:'#edf6ff',border:'1px solid rgba(148,163,184,.18)',borderRadius:10,padding:'11px 12px'};
const primary:React.CSSProperties={background:'linear-gradient(135deg,#1984ff,#1261df)',color:'#fff',border:0,borderRadius:10,padding:'11px 15px',fontWeight:800,cursor:'pointer'};
const secondary:React.CSSProperties={background:'transparent',color:'#c6d4e3',border:'1px solid rgba(148,163,184,.2)',borderRadius:10,padding:'11px 15px',cursor:'pointer'};
