"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import AdminStyles from "./AdminStyles";

type Row=Record<string,unknown>;
type ModuleKey="overview"|"users"|"transactions"|"wallets"|"ledger"|"deposits"|"withdrawals"|"disputes"|"support"|"notifications"|"revenue"|"invoices"|"settings"|"features"|"audit"|"admins"|"security";
type Setting={key:string;label:string;description:string;type:"number"|"boolean";value:number|boolean;unit?:string};
const MODULES:[ModuleKey,string,string][]=[
 ["overview","Dashboard","Vue générale"],["users","Utilisateurs","Comptes et profils"],["transactions","Transactions","Paiements et escrow"],["wallets","Wallets","Soldes"],["ledger","Ledger","Mouvements financiers"],["deposits","Dépôts","Recharges CinetPay"],["withdrawals","Retraits","Payouts"],["disputes","Litiges","Dossiers"],["support","Support","Tickets et messages"],["notifications","Notifications","Centre d'envoi"],["revenue","Revenus","Frais plateforme"],["invoices","Factures","Factures de transaction"],["settings","Paramètres","Configuration"],["features","Feature Flags","Fonctionnalités"],["audit","Audit Logs","Traçabilité"],["admins","Administrateurs","Accès admin"],["security","Sécurité","Contrôles"],
];
const DEFAULT_SETTINGS:Setting[]=[
 {key:"commission_rate_percent",label:"Commission SafePay",description:"Commission prélevée sur les transactions sécurisées.",type:"number",value:2,unit:"%"},{key:"deposit_fee_percent",label:"Frais de recharge",description:"Frais appliqués lors'une recharge.",type:"number",value:0,unit:"%"},{key:"withdrawal_fee_percent",label:"Frais de retrait",description:"Frais appliqués lors d'un retrait.",type:"number",value:0,unit:"%"},{key:"minimum_transaction_amount",label:"Transaction minimum",description:"Montant minimum autorisé.",type:"number",value:100,unit:"XOF"},{key:"maximum_transaction_amount",label:"Transaction maximum",description:"Montant maximum autorisé.",type:"number",value:1000000,unit:"XOF"},{key:"daily_withdrawal_limit",label:"Limite quotidienne de retrait",description:"Maximum retirable par jour.",type:"number",value:1000000,unit:"XOF"},{key:"maintenance_mode",label:"Mode maintenance",description:"Mettre temporairement l'application en maintenance.",type:"boolean",value:false},{key:"notifications_enabled",label:"Notifications globales",description:"Autoriser les notifications.",type:"boolean",value:true}
];
const FLAGS=[["new_signups_enabled","Nouvelles inscriptions","Autoriser la création de comptes."],["deposits_enabled","Recharges","Autoriser les recharges."],["withdrawals_enabled","Retraits","Autoriser les retraits."],["card_payments_enabled","Paiements par carte","Autoriser les paiements par carte."],["disputes_enabled","Litiges","Autoriser l'ouverture de litiges."]] as const;
function money(v:unknown){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"XOF",maximumFractionDigits:0}).format(Number(v??0));}
function display(v:unknown){if(v==null||v==="")return "—";if(typeof v==="boolean")return v?"Oui":"Non";if(typeof v==="object")return JSON.stringify(v);return String(v);}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="sp-admin-metric"><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}
function Chart({data}:{data:Row[]}){const max=Math.max(1,...data.map(x=>Number(x.transaction_volume??x.revenue??0)));return <div className="sp-chart">{data.map(x=><div className="sp-chart-col" key={String(x.date)} title={`${x.date}: ${money(x.transaction_volume)}`}><div className="sp-chart-bar" style={{height:`${Math.max(3,Number(x.transaction_volume??0)/max*100)}%`}}/><small>{String(x.date).slice(5)}</small></div>)}</div>}

export default function AdminPage(){
 const router=useRouter(); const [active,setActive]=useState<ModuleKey>("overview"); const [settings,setSettings]=useState(DEFAULT_SETTINGS); const [flags,setFlags]=useState<Record<string,boolean>>({}); const [reason,setReason]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [summary,setSummary]=useState<Row>({}); const [analytics,setAnalytics]=useState<Row[]>([]); const [rows,setRows]=useState<Row[]>([]); const [total,setTotal]=useState(0); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [page,setPage]=useState(0); const [selected,setSelected]=useState<Row|null>(null); const [days,setDays]=useState(30); const pageSize=25;
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace("/login?next=/admin");return;}const {data:isAdmin,error:ae}=await s.rpc("is_admin");if(ae||!isAdmin){setError("Accès administrateur requis.");setLoading(false);return;}const [{data:pub},{data:sum},{data:stats},{data:f}]=await Promise.all([s.rpc("get_public_settings"),s.rpc("get_admin_dashboard_summary"),s.rpc("admin_dashboard_stats"),s.from("feature_flags").select("key,enabled")]);if(pub)setSettings(DEFAULT_SETTINGS.map(x=>({...x,value:pub[x.key]??x.value})));setSummary({...sum,...stats});if(f)setFlags(Object.fromEntries(f.map(r=>[r.key,r.enabled])));setLoading(false);})().catch(e=>{setError(e instanceof Error?e.message:"Erreur de chargement");setLoading(false);})},[router]);
 useEffect(()=>{if(loading)return;setPage(0);loadModule(0);},[active,status,days]);
 useEffect(()=>{if(loading)return;const t=setTimeout(()=>loadModule(page),250);return()=>clearTimeout(t)},[search,page]);
 async function loadModule(p:number){const s=createClient();setRows([]);setError("");setMessage("");const q=search.trim()||null;let data:any=null,err:any=null;
  if(active==="users")({data,err}=await s.rpc("admin_list_users",{p_search:q,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="transactions")({data,err}=await s.rpc("admin_list_transactions",{p_search:q,p_status:status||null,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="wallets")({data,err}=await s.rpc("admin_list_wallets",{p_search:q,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="ledger")({data,err}=await s.rpc("admin_list_ledger",{p_search:q,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="deposits")({data,err}=await s.rpc("admin_list_deposits",{p_search:q,p_status:status||null,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="withdrawals")({data,err}=await s.rpc("admin_list_withdrawals",{p_search:q,p_status:status||null,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="disputes")({data,err}=await s.rpc("admin_list_disputes",{p_status:status||null,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="support")({data,err}=await s.rpc("admin_list_support_tickets",{p_status:status||null,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="audit")({data,err}=await s.rpc("admin_list_audit_logs",{p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="invoices")({data,err}=await s.rpc("admin_list_invoices",{p_search:q,p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="admins")({data,err}=await s.rpc("admin_list_admin_users",{p_limit:pageSize,p_offset:p*pageSize}));
  else if(active==="revenue"){const r=await s.rpc("admin_analytics_timeseries",{p_days:days});data={items:r.data};err=r.error;}
  if(err){setError(err.message);return;} const items=Array.isArray(data)?data:(data?.items??[]);setRows(items);setTotal(Number(data?.total??items.length));
 }
 async function action(label:string,fn:()=>PromiseLike<{error:any}>){setBusy(label);setError("");setMessage("");const r=await fn();if(r.error)setError(r.error.message);else setMessage("Action effectuée avec succès.");setBusy(null);await loadModule(page);}
 async function setAccount(userId:string,activeNow:boolean){const r=window.prompt(activeNow?"Motif de réactivation":"Motif de blocage",reason)||"Action Admin";await action(`account:${userId}`,()=>createClient().rpc("admin_set_account_status",{p_user_id:userId,p_is_active:activeNow,p_reason:r}));}
 async function reviewKyc(userId:string,approve:boolean){const r=window.prompt(approve?"Motif d'approbation KYC":"Motif du refus KYC",reason)||"Décision Admin";await action(`kyc:${userId}`,()=>createClient().rpc("admin_review_kyc",{p_user_id:userId,p_approve:approve,p_reason:r}));}
 async function notify(userId:string){const title=window.prompt("Titre de la notification");if(!title)return;const msg=window.prompt("Message");if(!msg)return;await action(`notify:${userId}`,()=>createClient().rpc("admin_send_notification",{p_title:title,p_message:msg,p_user_id:userId}));}
 async function save(item:Setting){await action(item.key,()=>createClient().rpc("admin_set_app_setting",{p_key:item.key,p_value_numeric:item.type==="number"?Number(item.value):null,p_value_text:null,p_value_boolean:item.type==="boolean"?Boolean(item.value):null,p_reason:reason.trim()||"Modification Admin"}));}
 async function toggleFlag(key:string,enabled:boolean){await action(key,()=>createClient().rpc("admin_set_feature_flag",{p_key:key,p_enabled:enabled,p_reason:reason.trim()||"Modification Admin"}));setFlags(x=>({...x,[key]:enabled}));}
 async function resolveDispute(id:string,actionName:string){const r=window.prompt("Décision / motif de résolution");if(!r)return;await action(`dispute:${id}`,()=>createClient().rpc("admin_resolve_dispute",{p_dispute_id:id,p_resolution:r,p_resolution_action:actionName}));}
 async function updateWithdrawal(id:string,next:string){const r=window.prompt("Motif du changement de statut");if(!r)return;await action(`withdrawal:${id}`,()=>createClient().rpc("admin_update_withdrawal_status",{p_withdrawal_id:id,p_status:next,p_reason:r}));}
 async function manageAdmin(id:string,act:string){const r=window.prompt("Motif de modification");if(!r)return;await action(`admin:${id}`,()=>createClient().rpc("admin_manage_admin_users",{p_target_user_id:id,p_action:act,p_role:"admin",p_reason:r}));}
 if(loading)return <main className="safepay-shell"><AdminStyles/><section className="sp-content"><p className="sp-muted">Chargement du Dashboard Admin…</p></section></main>;
 if(error==="Accès administrateur requis.")return <main className="safepay-shell"><AdminStyles/><section className="sp-content"><p className="sp-error">{error}</p><button className="safepay-primary" onClick={()=>router.push("/dashboard")}>Retour</button></section></main>;
 const moduleTitle=MODULES.find(m=>m[0]===active)?.[1]??"Administration";
 const columns=useMemo(()=>{const k=new Set<string>();rows.slice(0,25).forEach(r=>Object.keys(r).forEach(x=>k.add(x)));return [...k].filter(x=>x!=="details").slice(0,9)},[rows]);
 const renderActions=(r:Row)=>{const id=String(r.user_id??r.id??"");if(active==="users")return <><button className="safepay-secondary" onClick={()=>setSelected(r)}>Détails</button><button className="safepay-secondary" disabled={!!busy} onClick={()=>setAccount(id,Boolean(r.is_active)===false)}>{Boolean(r.is_active)===false?"Réactiver":"Bloquer"}</button><button className="safepay-secondary" disabled={!!busy} onClick={()=>notify(id)}>Notifier</button></>;if(active==="disputes")return <><button className="safepay-secondary" onClick={()=>setSelected(r)}>Examiner</button><button className="safepay-secondary" disabled={!!busy} onClick={()=>resolveDispute(id,"resolve")}>Résoudre</button></>;if(active==="withdrawals")return <><button className="safepay-secondary" onClick={()=>setSelected(r)}>Détails</button>{String(r.status)==="pending"&&<button className="safepay-secondary" disabled={!!busy} onClick={()=>updateWithdrawal(id,"processing")}>Traiter</button>}</>;if(active==="kyc")return <><button className="safepay-secondary" disabled={!!busy} onClick={()=>reviewKyc(id,true)}>Approuver</button><button className="safepay-secondary" disabled={!!busy} onClick={()=>reviewKyc(id,false)}>Refuser</button></>;if(active==="admins")return <><button className="safepay-secondary" onClick={()=>manageAdmin(id,"remove")}>Retirer</button></>;return <button className="safepay-secondary" onClick={()=>setSelected(r)}>Détails</button>};
 return <main className="safepay-shell safepay-dashboard"><AdminStyles/><header className="sp-header"><div><span className="sp-eyebrow">SafePay</span><strong>Admin Control Center</strong></div><div className="sp-header-actions"><button className="sp-back" onClick={()=>router.push("/dashboard")}>←</button></div></header><section className="sp-content">
  <div className="sp-admin-top"><div><p className="sp-eyebrow">Administration sécurisée</p><h1 className="sp-title">{moduleTitle}</h1><p className="sp-muted">Données réelles du backend SafePay. Les opérations financières passent par les fonctions sécurisées.</p></div><input className="sp-admin-search sp-global-search" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Recherche globale dans le module…"/></div>
  <nav className="sp-admin-nav">{MODULES.map(([key,label,desc])=><button key={key} className={active===key?"active":""} onClick={()=>{setActive(key);setSearch("");setStatus("");setPage(0);setMessage("")}}><strong>{label}</strong><small>{desc}</small></button>)}</nav>
  {message&&<p className="sp-success">{message}</p>}{error&&<p className="sp-error">{error}</p>}
  {active==="overview"&&<><section className="sp-section-card"><div className="sp-admin-metrics">{[["Utilisateurs",String(summary.users_total??summary.users??0)], ["Transactions",String(summary.transactions_total??summary.transactions??0)],["Volume terminé",money(summary.transactions_volume_total??summary.transaction_volume)],["Commissions",money(summary.commission_revenue_total??summary.commissions)],["Dépôts réussis",money(summary.deposits_volume_successful)],["Retraits réussis",money(summary.withdrawals_volume_successful)],["Fonds wallet",money(summary.wallets_total_balance)],["Fonds bloqués",money(summary.wallets_total_locked)],["Litiges ouverts",String(summary.disputes_open??summary.open_disputes??0)],["Retraits en attente",String(summary.withdrawals_pending_count??summary.pending_withdrawals??0)],["Dépôts en attente",String(summary.deposits_pending_count??0)],["Tickets ouverts",String(summary.support_tickets_open??0)]].map(([l,v])=><Metric key={l} label={l} value={v}/>)}</div></section><section className="sp-section-card"><div className="sp-section-head"><div><h2>Activité</h2><p className="sp-muted">Volume des transactions terminées par jour.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 jours</option><option value={30}>30 jours</option><option value={90}>90 jours</option><option value={365}>12 mois</option></select></div><AnalyticsChart days={days}/></section></>}
  {active==="notifications"&&<NotificationPanel onDone={()=>{setMessage("Notification envoyée.");}}/>}
  {active==="settings"&&<SettingsPanel settings={settings} setSettings={setSettings} reason={reason} setReason={setReason} busy={busy} save={save}/>} 
  {active==="features"&&<FeaturePanel flags={flags} reason={reason} setReason={setReason} toggle={toggleFlag}/>} 
  {active==="security"&&<SecurityPanel/>}
  {active!=="overview"&&active!=="notifications"&&active!=="settings"&&active!=="features"&&active!=="security"&&<><div className="sp-admin-toolbar">{["transactions","deposits","withdrawals","disputes","support"].includes(active)&&<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">Tous les statuts</option>{(active==="transactions"?["pending","funded","delivered","completed","disputed","cancelled"]:active==="deposits"?["pending","processing","successful","failed","cancelled"]:active==="withdrawals"?["pending","processing","successful","failed","cancelled"]:active==="disputes"?["open","resolved_buyer","resolved_seller","rejected"]:["open","in_progress","resolved","closed"]).map(x=><option key={x} value={x}>{x}</option>)}</select>}{active==="revenue"&&<span className="sp-muted">Les revenus proviennent de platform_fees.</span>}</div><section className="sp-section-card"><div className="sp-admin-table-wrap"><table className="sp-admin-table"><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}<th>Actions</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={columns.length+1}>Aucune donnée.</td></tr>:rows.map((r,i)=><tr key={String(r.id??r.user_id??i)}>{columns.map(c=><td key={c}>{display(r[c])}</td>)}<td className="sp-actions">{renderActions(r)}</td></tr>)}</tbody></table></div><div className="sp-pagination"><span>{total} résultat(s)</span><button className="safepay-secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>Page {page+1}</span><button className="safepay-secondary" disabled={(page+1)*pageSize>=total && total>0} onClick={()=>setPage(p=>p+1)}>Suivant</button></div></section></>}
  {selected&&<div className="sp-admin-modal" onClick={()=>setSelected(null)}><div className="sp-admin-modal-card" onClick={e=>e.stopPropagation()}><div className="sp-section-head"><h2>Détails</h2><button className="sp-back" onClick={()=>setSelected(null)}>×</button></div><pre>{JSON.stringify(selected,null,2)}</pre></div></div>}
 </section></main>;
}

function AnalyticsChart({days}:{days:number}){const [data,setData]=useState<Row[]>([]);useEffect(()=>{createClient().rpc("admin_analytics_timeseries",{p_days:days}).then(({data,error})=>{if(!error&&Array.isArray(data))setData(data)})},[days]);return <Chart data={data}/>}
function SettingsPanel({settings,setSettings,reason,setReason,busy,save}:{settings:Setting[];setSettings:any;reason:string;setReason:any;busy:string|null;save:(s:Setting)=>Promise<void>}){return <><section className="sp-section-card"><label className="sp-form"><span>Motif de modification</span><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex. ajustement tarifaire"/></label><div className="sp-admin-settings">{settings.map(item=><div className="sp-admin-setting" key={item.key}><div><strong>{item.label}</strong><small>{item.description}</small></div>{item.type==="number"?<div className="sp-admin-control"><input type="number" min="0" step="0.01" value={String(item.value)} onChange={e=>setSettings((a:Setting[])=>a.map(x=>x.key===item.key?{...x,value:Number(e.target.value)}:x))}/><span>{item.unit}</span><button className="safepay-primary" disabled={busy===item.key} onClick={()=>save(item)}>Enregistrer</button></div>:<button className="safepay-secondary" onClick={()=>{const next=!Boolean(item.value);const changed={...item,value:next};setSettings((a:Setting[])=>a.map(x=>x.key===item.key?changed:x));save(changed)}}>{item.value?"Activé":"Désactivé"}</button>}</div>)}</div></section></>}
function FeaturePanel({flags,reason,setReason,toggle}:{flags:Record<string,boolean>;reason:string;setReason:any;toggle:(k:string,v:boolean)=>Promise<void>}){return <section className="sp-section-card"><label className="sp-form"><span>Motif de modification</span><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motif obligatoire pour les changements sensibles"/></label><div className="sp-admin-settings">{FLAGS.map(([key,label,desc])=><div className="sp-admin-setting" key={key}><div><strong>{label}</strong><small>{desc}</small></div><button className="safepay-secondary" onClick={()=>toggle(key,!Boolean(flags[key]))}>{flags[key]?"Activé":"Désactivé"}</button></div>)}</div></section>}
function SecurityPanel(){return <section className="sp-section-card"><div className="sp-security-grid"><Metric label="Autorisation" value="Supabase Auth + is_admin()"/><Metric label="RLS" value="Activé"/><Metric label="Service role frontend" value="Interdit"/><Metric label="Wallet direct update" value="Interdit"/></div><p className="sp-muted">Les actions sensibles utilisent les fonctions SQL Admin sécurisées. Aucun secret CinetPay, Bird ou service_role n'est affiché dans cette interface.</p></section>}
function NotificationPanel({onDone}:{onDone:()=>void}){const [userId,setUserId]=useState("");const [title,setTitle]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const send=async()=>{if(!userId||!title||!msg)return;setBusy(true);const {error}=await createClient().rpc("admin_send_notification",{p_title:title,p_message:msg,p_user_id:userId});setBusy(false);if(error)alert(error.message);else{setTitle("");setMsg("");onDone()}};return <section className="sp-section-card"><h2>Notification ciblée</h2><p className="sp-muted">L'envoi utilise le backend réel. Aucune notification locale n'est créée.</p><div className="sp-form"><label>UUID utilisateur<input value={userId} onChange={e=>setUserId(e.target.value)} placeholder="user_id"/></label><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea value={msg} onChange={e=>setMsg(e.target.value)} rows={5}/></label><button className="safepay-primary" disabled={busy} onClick={send}>{busy?"Envoi…":"Envoyer"}</button></div></section>}
