"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import AdminStyles from "./AdminStyles";
type Setting={key:string;label:string;description:string;type:"number"|"boolean";value:number|boolean;unit?:string}; type Row=Record<string,unknown>;
type ModuleKey="overview"|"users"|"transactions"|"wallets"|"deposits"|"withdrawals"|"disputes"|"kyc"|"audit"|"settings";
const DEFAULT_SETTINGS:Setting[]=[{key:"commission_rate_percent",label:"Commission SafePay",description:"Commission prélevée sur les transactions sécurisées.",type:"number",value:2,unit:"%"},{key:"deposit_fee_percent",label:"Frais de recharge",description:"Frais appliqués lors d'une recharge.",type:"number",value:0,unit:"%"},{key:"withdrawal_fee_percent",label:"Frais de retrait",description:"Frais appliqués lors d'un retrait.",type:"number",value:0,unit:"%"},{key:"minimum_transaction_amount",label:"Transaction minimum",description:"Montant minimum autorisé.",type:"number",value:100,unit:"XOF"},{key:"maximum_transaction_amount",label:"Transaction maximum",description:"Montant maximum autorisé.",type:"number",value:1000000,unit:"XOF"},{key:"daily_withdrawal_limit",label:"Limite quotidienne de retrait",description:"Maximum retirable par jour.",type:"number",value:1000000,unit:"XOF"},{key:"maintenance_mode",label:"Mode maintenance",description:"Mettre temporairement l'application en maintenance.",type:"boolean",value:false},{key:"notifications_enabled",label:"Notifications globales",description:"Autoriser les notifications.",type:"boolean",value:true}];
const FLAGS=[["new_signups_enabled","Nouvelles inscriptions","Autoriser la création de comptes."],["deposits_enabled","Recharges","Autoriser les recharges."],["withdrawals_enabled","Retraits","Autoriser les retraits."],["card_payments_enabled","Paiements par carte","Autoriser les paiements par carte."],["disputes_enabled","Litiges","Autoriser l'ouverture de litiges."]] as const;
const MODULES:[ModuleKey,string,string][]=[["overview","Vue générale","Statistiques SafePay"],["users","Utilisateurs","Comptes et profils"],["transactions","Transactions","Paiements et opérations"],["wallets","Wallets","Soldes et mouvements"],["deposits","Recharges","Dépôts et entrées"],["withdrawals","Retraits","Demandes de retrait"],["disputes","Litiges","Dossiers à traiter"],["kyc","KYC","Vérifications"],["audit","Journal Admin","Traçabilité des actions"],["settings","Paramètres","Configuration"]];
function money(v:unknown){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"XOF",maximumFractionDigits:0}).format(Number(v??0));} function display(v:unknown){if(v==null||v==="")return "—";if(typeof v==="boolean")return v?"Oui":"Non";if(typeof v==="object")return JSON.stringify(v);return String(v);}
function Metric({label,value}:{label:string;value:string}){return <div className="sp-admin-metric"><small>{label}</small><strong>{value}</strong></div>}
export default function AdminPage(){const router=useRouter();const[active,setActive]=useState<ModuleKey>("overview");const[settings,setSettings]=useState(DEFAULT_SETTINGS);const[flags,setFlags]=useState<Record<string,boolean>>({});const[reason,setReason]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");const[summary,setSummary]=useState<Row|null>(null);const[rows,setRows]=useState<Row[]>([]);const[rowsError,setRowsError]=useState("");const[search,setSearch]=useState("");
useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace("/login?next=/admin");return;}const{data:a,error:ae}=await s.rpc("is_admin");if(ae||!a){setError("Accès administrateur requis.");setLoading(false);return;}const[{data:st,error:ste},{data:sum,error:se},{data:f,error:fe}]=await Promise.all([s.rpc("get_public_settings"),s.rpc("get_admin_dashboard_summary"),s.from("feature_flags").select("key,enabled")]);if(ste||se||fe)setError((ste||se||fe)?.message||"");if(st)setSettings(DEFAULT_SETTINGS.map(x=>({...x,value:st[x.key]??x.value})));if(sum)setSummary(sum);if(f)setFlags(Object.fromEntries(f.map(r=>[r.key,r.enabled])));setLoading(false);})().catch(e=>{setError(e instanceof Error?e.message:"Erreur de chargement");setLoading(false);})},[router]);
useEffect(()=>{if(active==="overview"||active==="settings")return;let cancelled=false;(async()=>{setRows([]);setRowsError("");const s=createClient();const q=search.trim()||null;let data:any,error:any;if(active==="users")({data,error}=await s.rpc("admin_list_users",{p_search:q,p_limit:100,p_offset:0}));else if(active==="transactions")({data,error}=await s.rpc("admin_list_transactions",{p_search:q,p_status:null,p_limit:100,p_offset:0}));else if(active==="wallets")({data,error}=await s.rpc("admin_list_wallets",{p_search:q,p_limit:100,p_offset:0}));else if(active==="deposits")({data,error}=await s.rpc("admin_list_deposits",{p_search:q,p_status:null,p_limit:100,p_offset:0}));else if(active==="withdrawals")({data,error}=await s.rpc("admin_list_withdrawals",{p_search:q,p_status:null,p_limit:100,p_offset:0}));else if(active==="disputes")({data,error}=await s.rpc("admin_list_disputes",{p_status:null,p_limit:100,p_offset:0}));else if(active==="kyc")({data,error}=await s.rpc("admin_list_kyc",{p_status:null,p_limit:100,p_offset:0}));else if(active==="audit")({data,error}=await s.rpc("admin_list_audit_logs",{p_limit:100,p_offset:0}));if(cancelled)return;if(error)setRowsError(error.message);else setRows(Array.isArray(data?.items)?data.items:[]);})();return()=>{cancelled=true}},[active,search]);
const columns=useMemo(()=>{const k=new Set<string>();rows.slice(0,30).forEach(r=>Object.keys(r).forEach(x=>k.add(x)));return [...k].slice(0,8)},[rows]);
async function action(label:string,fn:()=>PromiseLike<{error:any}>){setBusy(label);setError("");setMessage("");const r=await fn();if(r.error)setError(r.error.message);else setMessage("Action effectuée avec succès.");setBusy(null);}
async function setAccount(userId:string,active:boolean){const reasonText=window.prompt(active?"Motif de réactivation":"Motif de blocage",reason)||"Action Admin";if(reasonText===null)return;await action(`account:${userId}`,()=>createClient().rpc("admin_set_account_status",{p_user_id:userId,p_is_active:active,p_reason:reasonText}));}
async function reviewKyc(userId:string,approve:boolean){const reasonText=window.prompt(approve?"Motif d'approbation KYC":"Motif du refus KYC",reason)||"Décision Admin";if(reasonText===null)return;await action(`kyc:${userId}`,()=>createClient().rpc("admin_review_kyc",{p_user_id:userId,p_approve:approve,p_reason:reasonText}));}
async function notify(userId:string){const title=window.prompt("Titre de la notification");if(!title)return;const msg=window.prompt("Message");if(!msg)return;await action(`notify:${userId}`,()=>createClient().rpc("admin_send_notification",{p_title:title,p_message:msg,p_user_id:userId}));}
async function save(item:Setting){await action(item.key,()=>createClient().rpc("admin_set_app_setting",{p_key:item.key,p_value_numeric:item.type==="number"?Number(item.value):null,p_value_text:null,p_value_boolean:item.type==="boolean"?Boolean(item.value):null,p_reason:reason.trim()||"Modification Admin"}));}
async function toggleFlag(key:string,enabled:boolean){await action(key,()=>createClient().rpc("admin_set_feature_flag",{p_key:key,p_enabled:enabled,p_reason:reason.trim()||"Modification Admin"}));if(!error)setFlags(x=>({...x,[key]:enabled}));}
if(loading)return <main className="safepay-shell"><AdminStyles/><section className="sp-content"><p className="sp-muted">Chargement du Dashboard Admin…</p></section></main>;
if(error==="Accès administrateur requis.")return <main className="safepay-shell"><AdminStyles/><section className="sp-content"><p className="sp-error">{error}</p><button className="safepay-primary" onClick={()=>router.push("/dashboard")}>Retour</button></section></main>;
return <main className="safepay-shell safepay-dashboard"><AdminStyles/><header className="sp-header"><div><span className="sp-eyebrow">SafePay</span><strong>Dashboard Admin</strong></div><button className="sp-back" onClick={()=>router.push("/dashboard")} aria-label="Retour">←</button></header><section className="sp-content"><div className="sp-admin-nav">{MODULES.map(([key,label,desc])=><button key={key} className={active===key?"active":""} onClick={()=>{setActive(key);setSearch("");setMessage("")}}><strong>{label}</strong><small>{desc}</small></button>)}</div>{message&&<p className="sp-success">{message}</p>}{error&&<p className="sp-error">{error}</p>}
{active==="overview"&&<><p className="sp-eyebrow">Administration</p><h1 className="sp-title">Vue générale</h1><p className="sp-muted">Supervision de l'activité SafePay.</p>{summary&&<section className="sp-section-card"><div className="sp-admin-metrics">{[["Commissions",money(summary.commissions)],["Volume",money(summary.transaction_volume)],["Utilisateurs",String(summary.users??0)],["Transactions",String(summary.transactions??0)],["Fonds bloqués",money(summary.escrow_locked)],["Litiges ouverts",String(summary.open_disputes??0)],["Retraits en attente",String(summary.pending_withdrawals??0)],["KYC en attente",String(summary.pending_kyc??0)]].map(([l,v])=><Metric key={l} label={l} value={v}/>)}</div></section>}</>}
{active!=="overview"&&active!=="settings"&&<section className="sp-section-card"><p className="sp-eyebrow">Administration</p><h1 className="sp-title">{MODULES.find(m=>m[0]===active)?.[1]}</h1><p className="sp-muted">Données réelles via Supabase.</p><input className="sp-admin-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher…"/>{rowsError?<p className="sp-error">{rowsError}</p>:rows.length===0?<p className="sp-muted">Aucune donnée trouvée.</p>:<div className="sp-admin-table-wrap"><table className="sp-admin-table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}{(active==="users"||active==="kyc")&&<th>Actions</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)}>{columns.map(c=><td key={c}>{display(row[c])}</td>)}{active==="users"&&<td><button className="safepay-secondary" disabled={!!busy} onClick={()=>setAccount(String(row.user_id??row.id),Boolean(row.is_active)===false)}> {Boolean(row.is_active)===false?"Réactiver":"Bloquer"}</button><button className="safepay-secondary" disabled={!!busy} onClick={()=>notify(String(row.user_id??row.id))}>Notifier</button></td>}{active==="kyc"&&<td><button className="safepay-secondary" disabled={!!busy} onClick={()=>reviewKyc(String(row.user_id??row.id),true)}>Approuver</button><button className="safepay-secondary" disabled={!!busy} onClick={()=>reviewKyc(String(row.user_id??row.id),false)}>Refuser</button></td>}</tr>)}</tbody></table></div>}</section>}
{active==="settings"&&<><p className="sp-eyebrow">Administration</p><h1 className="sp-title">Configuration</h1><section className="sp-section-card"><label className="sp-form"><span>Motif de modification</span><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex. ajustement tarifaire"/></label><div className="sp-admin-settings">{settings.map(item=><div className="sp-admin-setting" key={item.key}><div><strong>{item.label}</strong><small>{item.description}</small></div>{item.type==="number"?<div className="sp-admin-control"><input type="number" min="0" step="0.01" value={String(item.value)} onChange={e=>setSettings(a=>a.map(x=>x.key===item.key?{...x,value:Number(e.target.value)}:x))}/><span>{item.unit}</span><button className="safepay-primary" disabled={busy===item.key} onClick={()=>save(item)}>Enregistrer</button></div>:<button className="safepay-secondary" onClick={()=>{const next=!Boolean(item.value);setSettings(a=>a.map(x=>x.key===item.key?{...x,value:next}:x));save({...item,value:next})}}>{item.value?"Activé":"Désactivé"}</button>}</div>)}</div></section><section className="sp-section-card"><h2>Feature flags</h2><div className="sp-admin-settings">{FLAGS.map(([key,label,desc])=><div className="sp-admin-setting" key={key}><div><strong>{label}</strong><small>{desc}</small></div><button className="safepay-secondary" onClick={()=>toggleFlag(key,!Boolean(flags[key]))}>{flags[key]?"Activé":"Désactivé"}</button></div>)}</div></section></>}
</section></main>;
}