"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useParams, useRouter } from "next/navigation";

type Row = Record<string, any>;
const money=(v:any)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"XOF",maximumFractionDigits:0}).format(Number(v??0));
const fmt=(v:any)=>v?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";

export default function AdminDisputeDetail(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [data,setData]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [choice,setChoice]=useState("refund_buyer"); const [resolution,setResolution]=useState(""); const [notice,setNotice]=useState("");
 async function load(){setLoading(true);setNotice("");const s=createClient();const gate=await s.rpc("is_admin");if(gate.error||!gate.data){router.replace("/login?next=/admin/disputes/"+encodeURIComponent(id));return;}const r=await s.rpc("admin_get_dispute_detail",{p_dispute_id:id});if(r.error)setNotice(r.error.message);else setData(r.data);setLoading(false)}
 useEffect(()=>{if(id)load()},[id]);
 async function contactUser(){if(!data?.user?.id||!message.trim())return;setBusy(true);setNotice("");const s=createClient();const text=message.trim();const n=await s.rpc("admin_send_notification",{p_user_id:data.user.id,p_title:"Votre litige SafePay",p_message:text});const sms=await s.functions.invoke("bird-sms",{body:{phone:data.user.phone,message:text,category:"service"}});if(n.error&&sms.error)setNotice("Impossible d'envoyer le message.");else setNotice(sms.error?"Notification envoyée. SMS indisponible pour le moment.":"Message envoyé par notification et SMS.");setMessage("");setBusy(false)}
 async function resolve(){if(!resolution.trim())return;setBusy(true);setNotice("");const s=createClient();const r=await s.rpc("admin_resolve_dispute",{p_dispute_id:id,p_resolution:resolution.trim(),p_resolution_action:choice});if(r.error)setNotice(r.error.message);else {setNotice("Litige traité avec succès.");await load()}setBusy(false)}
 if(loading)return <main style={{padding:32,fontFamily:"Inter,system-ui"}}>Chargement du litige…</main>;
 if(!data)return <main style={{padding:32,fontFamily:"Inter,system-ui"}}><p>{notice||"Litige introuvable."}</p><a href="/admin">← Dashboard</a></main>;
 const d=data.dispute||{},u=data.user||{},t=data.transaction||{},evidence=Array.isArray(data.evidence)?data.evidence:[],events=Array.isArray(data.events)?data.events:[];
 return <main style={{minHeight:"100vh",background:"#06101f",color:"#f4f8ff",fontFamily:"Inter,system-ui",padding:"28px 22px 60px"}}><div style={{maxWidth:1180,margin:"0 auto"}}><a href="/admin" style={{color:"#7fc0ff",textDecoration:"none"}}>← Dashboard Admin</a><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",margin:"22px 0"}}><div><div style={{fontSize:11,letterSpacing:".16em",color:"#59a9ff",fontWeight:900}}>LITIGE • DOSSIER SÉCURISÉ</div><h1 style={{margin:"7px 0",fontSize:34}}>Litige de {u.full_name||u.phone||d.opened_by}</h1><p style={{margin:0,color:"#8fa6bf"}}>Ouvert le {fmt(d.created_at)} · Statut : <b>{d.status}</b></p></div><div style={{padding:"9px 13px",borderRadius:20,background:"rgba(22,119,255,.12)",color:"#9bd0ff"}}>Backend Supabase</div></div>
 {notice&&<div style={{padding:13,borderRadius:12,background:"rgba(31,132,255,.1)",border:"1px solid rgba(31,132,255,.2)",marginBottom:16}}>{notice}</div>}
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
  <section style={card}><h2>Client</h2><KV items={[["Nom",u.full_name],["Téléphone",u.phone],["Pays",u.country],["Rôle",u.role]]}/></section>
  <section style={card}><h2>Transaction</h2><KV items={[["ID",t.id],["Montant",money(t.amount)],["Commission",money(t.commission)],["Statut",t.status],["Description",t.description]]}/></section>
  <section style={{...card,gridColumn:"1 / -1"}}><h2>Problème signalé</h2><div style={{padding:14,borderRadius:12,background:"#071525",lineHeight:1.6}}><b>{d.reason||"Motif non renseigné"}</b><p style={{whiteSpace:"pre-wrap",margin:"10px 0 0",color:"#c6d4e3"}}>{d.description||"Aucune description détaillée."}</p></div></section>
  <section style={{...card,gridColumn:"1 / -1"}}><h2>Preuves / photos</h2>{evidence.length?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))",gap:12}}>{evidence.map((ev:Row)=><Evidence key={ev.id} ev={ev}/>)}</div>:<p style={{color:"#8fa6bf"}}>Aucune preuve photo enregistrée pour ce dossier.</p>}</section>
  <section style={card}><h2>Contacter le client</h2><p style={{color:"#8fa6bf",fontSize:13}}>Le message est envoyé dans SafePay et, si le service SMS est configuré, directement sur son numéro.</p><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Écrire au client…" style={textarea}/><button onClick={contactUser} disabled={busy||!message.trim()} style={primary}>{busy?"Envoi…":"Envoyer le message"}</button></section>
  <section style={card}><h2>Traitement du litige</h2><select value={choice} onChange={e=>setChoice(e.target.value)} style={input}><option value="refund_buyer">Rembourser l'acheteur</option><option value="release_seller">Libérer au vendeur</option></select><textarea value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Décision et justification…" style={{...textarea,marginTop:10}}/><button onClick={resolve} disabled={busy||!resolution.trim()||["resolved_buyer","resolved_seller","closed"].includes(d.status)} style={primary}>{busy?"Traitement…":"Valider la décision"}</button></section>
  <section style={{...card,gridColumn:"1 / -1"}}><h2>Historique des échanges / événements</h2>{events.length?<div>{events.map((ev:Row)=><div key={ev.id} style={{padding:"11px 0",borderBottom:"1px solid rgba(148,163,184,.12)"}}><b>{ev.event_type||"Événement"}</b><span style={{float:"right",color:"#8fa6bf",fontSize:12}}>{fmt(ev.created_at)}</span><pre style={{whiteSpace:"pre-wrap",color:"#a9bdd1",fontSize:12}}>{JSON.stringify(ev.details||{},null,2)}</pre></div>)}</div>:<p style={{color:"#8fa6bf"}}>Aucun événement supplémentaire.</p>}</section>
 </div></div></main>
}
const card:React.CSSProperties={background:"rgba(10,24,43,.9)",border:"1px solid rgba(82,168,255,.14)",borderRadius:18,padding:20,boxShadow:"0 18px 55px rgba(0,0,0,.18)"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#071525",color:"#edf6ff",border:"1px solid rgba(148,163,184,.18)",borderRadius:10,padding:"11px 12px"};
const textarea:React.CSSProperties={...input,minHeight:110,resize:"vertical"};
const primary:React.CSSProperties={marginTop:10,background:"linear-gradient(135deg,#1984ff,#1261df)",color:"#fff",border:0,borderRadius:10,padding:"11px 15px",fontWeight:800,cursor:"pointer"};
function KV({items}:{items:any[]}){return <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{items.map(([k,v])=><div key={k} style={{padding:10,borderRadius:10,background:"#071525"}}><small style={{display:"block",color:"#7f96ad"}}>{k}</small><strong style={{display:"block",marginTop:4,wordBreak:"break-word"}}>{v??"—"}</strong></div>)}</div>}
function Evidence({ev}:{ev:Row}){const [url,setUrl]=useState("");useEffect(()=>{(async()=>{const s=createClient();if(ev.file_url){setUrl(ev.file_url);return;}const r=await s.storage.from("dispute-evidence").createSignedUrl(ev.file_path,3600);if(!r.error)setUrl(r.data.signedUrl)})()},[ev]);return <div style={{borderRadius:12,overflow:"hidden",background:"#071525",border:"1px solid rgba(148,163,184,.12)"}}>{url?<img src={url} alt={ev.caption||"Preuve du litige"} style={{width:"100%",height:160,objectFit:"cover"}}/>:<div style={{height:160,display:"grid",placeItems:"center",color:"#8fa6bf"}}>Chargement…</div>}<div style={{padding:9,fontSize:11,color:"#a9bdd1"}}>{ev.caption||ev.media_type||"Preuve"}<br/>{fmt(ev.created_at)}</div></div>}
