"use client";
import { useEffect,useState } from "react";
import { AppShell } from "@/components/navigation/AppShell";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

type Dispute={id:string;transaction_id:string;reason:string;status:string;resolution:string|null;created_at:string};
const labels:Record<string,string>={open:"Ouvert",resolved_buyer:"Remboursé",resolved_seller:"Résolu vendeur",under_review:"En examen"};
export default function DisputesPage(){const router=useRouter();const [items,setItems]=useState<Dispute[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{let active=true;(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Session expirée. Reconnectez-vous.");setLoading(false);return;}const {data,error:e}=await s.from("disputes").select("id,transaction_id,reason,status,resolution,created_at").eq("opened_by",user.id).order("created_at",{ascending:false});if(!active)return;if(e)setError(e.message);else setItems((data??[]) as Dispute[]);setLoading(false)})();return()=>{active=false}},[]);return <AppShell><section className="sp-page"><p className="sp-eyebrow">Protection SafePay</p><h1 className="sp-title">Mes litiges</h1>{loading?<div className="sp-page-loading" role="status"><span className="sp-loader"/></div>:error?<p className="sp-form-error">{error}</p>:items.length===0?<section className="sp-section-card sp-empty-list"><strong>Aucun litige</strong><span>Les dossiers ouverts sur vos transactions apparaîtront ici.</span></section>:<section className="sp-notification-list">{items.map(d=><button className="sp-notification-row" key={d.id} onClick={()=>router.push(`/transactions/${d.transaction_id}`)}><span className="sp-notification-dot"/><span><strong>{labels[d.status]??d.status}</strong><small>{d.reason}</small><small>{new Date(d.created_at).toLocaleString("fr-FR")}</small></span></button>)}</section>}</section></AppShell>}
