"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function AdminControlCenter(){
 const [theme,setTheme]=useState("system"),[language,setLanguage]=useState("fr"),[currency,setCurrency]=useState("XOF"),[days,setDays]=useState(30),[start,setStart]=useState(""),[end,setEnd]=useState(""),[series,setSeries]=useState<any[]>([]),[admins,setAdmins]=useState<any[]>([]),[settings,setSettings]=useState<any[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{const t=localStorage.getItem("safepay-admin-theme")||"system",l=localStorage.getItem("safepay-admin-language")||"fr",c=localStorage.getItem("safepay-admin-currency")||"XOF";setTheme(t);setLanguage(l);setCurrency(c);document.documentElement.dataset.theme=t},[]);
 const pref=(key:string,value:string)=>{localStorage.setItem(key,value);if(key.includes("theme")){setTheme(value);document.documentElement.dataset.theme=value}if(key.includes("language"))setLanguage(value);if(key.includes("currency"))setCurrency(value)};
 async function load(){const s=createClient();const p:any={p_days:days};if(start)p.p_start_date=start;if(end)p.p_end_date=end;const [a,b,c]=await Promise.all([s.rpc("admin_analytics_timeseries",p),s.rpc("admin_list_admin_users"),s.rpc("get_public_settings")]);if(!a.error)setSeries(Array.isArray(a.data)?a.data:[]);if(!b.error)setAdmins(Array.isArray(b.data)?b.data:[]);if(!c.error&&c.data)setSettings(Object.entries(c.data).map(([key,value])=>({key,value})))}
 useEffect(()=>{load()},[days,start,end]);
 const values=series.map(x=>Number(x.revenue??x.platform_revenue??x.fees??0));const max=Math.max(1,...values);const revenue=values.reduce((a,b)=>a+b,0);
 async function addAdmin(){const phone=prompt("Téléphone du nouvel administrateur (+228...)");if(!phone)return;const role=prompt("Rôle : super_admin, admin, support ou finance","admin")||"admin";const r=await createClient().rpc("admin_manage_admin_users",{p_action:"add",p_phone:phone,p_role:role,p_reason:"Ajout depuis le centre administrateur"});setMessage(r.error?r.error.message:"Administrateur ajouté avec succès.");load()}
 return <main style={{minHeight:"100vh",background:"var(--admin-bg,#07101d)",color:"var(--admin-text,#eef6ff)",padding:24,fontFamily:"system-ui"}}><div style={{maxWidth:1400,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",marginBottom:24,flexWrap:"wrap"}}><div><div style={{fontWeight:900,fontSize:24}}>SAFE<span style={{color:"#42a5ff"}}>PAY</span> <small style={{fontSize:12}}>ADMIN CONTROL CENTER</small></div><p style={{opacity:.65}}>Analytics, préférences et administration connectés au backend SafePay.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><select value={theme} onChange={e=>pref("safepay-admin-theme",e.target.value)}><option value="system">Système</option><option value="light">Clair</option><option value="dark">Sombre</option></select><select value={language} onChange={e=>pref("safepay-admin-language",e.target.value)}><option value="fr">🇫🇷 Français</option><option value="en">🇬🇧 English</option></select><select value={currency} onChange={e=>pref("safepay-admin-currency",e.target.value)}><option>XOF</option><option>EUR</option><option>USD</option></select></div></header>
 <section style={{background:"rgba(20,35,55,.75)",border:"1px solid rgba(100,170,255,.16)",borderRadius:20,padding:22,marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h2>📊 Trafic & revenus</h2><p style={{opacity:.65}}>Période personnalisable avec données de la base SafePay.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 jours</option><option value={30}>30 jours</option><option value={90}>90 jours</option><option value={365}>1 an</option></select></div></div><div style={{fontSize:30,fontWeight:800,margin:"18px 0"}}>{new Intl.NumberFormat("fr-FR").format(revenue)} XOF <small style={{fontSize:13,opacity:.6}}>revenus plateforme</small></div><div style={{height:240,display:"flex",alignItems:"end",gap:4,borderBottom:"1px solid #28405a",padding:"10px 4px"}}>{values.map((v,i)=><div key={i} title={`${series[i]?.date??i+1}: ${v.toLocaleString()} XOF`} style={{flex:1,maxWidth:22,height:`${Math.max(3,v/max*100)}%`,background:"linear-gradient(180deg,#48a9ff,#1461d2)",borderRadius:"6px 6px 0 0"}}/>)}</div></section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:20}}><article style={{background:"rgba(20,35,55,.75)",border:"1px solid rgba(100,170,255,.16)",borderRadius:20,padding:22}}><h2>⚙️ Préférences</h2><p>Thème, langue et devise du Dashboard.</p><div style={{display:"grid",gap:10}}><label>Thème <select value={theme} onChange={e=>pref("safepay-admin-theme",e.target.value)}><option value="system">Système</option><option value="light">Clair</option><option value="dark">Sombre</option></select></label><label>Langue <select value={language} onChange={e=>pref("safepay-admin-language",e.target.value)}><option value="fr">Français</option><option value="en">English</option></select></label><label>Devise <select value={currency} onChange={e=>pref("safepay-admin-currency",e.target.value)}><option>XOF</option><option>EUR</option><option>USD</option></select></label></div></article><article style={{background:"rgba(20,35,55,.75)",border:"1px solid rgba(100,170,255,.16)",borderRadius:20,padding:22}}><h2>👨‍💼 Administrateurs</h2><p>Gestion des accès via la fonction administrative SafePay.</p><button onClick={addAdmin} style={{padding:"12px 16px",border:0,borderRadius:10,background:"#1677e8",color:"white",fontWeight:700}}>+ Ajouter un administrateur</button>{message&&<p>{message}</p>}<ul>{admins.map((a,i)=><li key={a.user_id||i}>{a.name||"—"} · {a.phone||"—"} · {a.role||"—"}</li>)}</ul></article><article style={{background:"rgba(20,35,55,.75)",border:"1px solid rgba(100,170,255,.16)",borderRadius:20,padding:22}}><h2>🔐 Paramètres SafePay</h2><p>Lecture des paramètres réels du backend.</p><div style={{maxHeight:260,overflow:"auto"}}>{settings.map((x,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.08)"}}><span>{x.key}</span><b>{String(x.value)}</b></div>)}</div></article></section></div></main>
}
