import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders}); if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const authHeader=req.headers.get("Authorization"); if(!authHeader)return json({error:"not_authenticated"},401);
 const url=Deno.env.get("SUPABASE_URL"); const anonKey=Deno.env.get("SUPABASE_ANON_KEY"); if(!url||!anonKey)return json({error:"supabase_configuration_missing"},500);
 const supabase=createClient(url,anonKey,{global:{headers:{Authorization:authHeader}}}); const {data:{user},error:userError}=await supabase.auth.getUser(); if(userError||!user)return json({error:"not_authenticated"},401);
 let body:{transaction_id?:string;action?:string;reason?:string;description?:string}; try{body=await req.json()}catch{return json({error:"invalid_json"},400)}
 const transactionId=body.transaction_id?.trim(),action=body.action?.trim(); if(!transactionId||!action)return json({error:"transaction_id_and_action_required"},400);
 const notify=async(status:string)=>{const {data:tx}=await supabase.from("transactions").select("id,amount,currency,account_id,seller_id").eq("id",transactionId).maybeSingle();if(!tx)return{attempted:0,sent:0};const {data:account}=await supabase.from("accounts").select("user_id").eq("id",tx.account_id).maybeSingle();const ids=[...new Set([account?.user_id,tx.seller_id].filter(Boolean))] as string[];if(!ids.length)return{attempted:0,sent:0};const {data:profiles}=await supabase.from("profiles").select("id,phone").in("id",ids);let sent=0;for(const p of profiles??[]){if(!p.phone)continue;const amount=new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(Number(tx.amount??0));const text=`SafePay: transaction ${amount} ${tx.currency||"XOF"} — statut: ${status}. ID: ${transactionId.slice(0,8)}.`;const sms=await fetch(`${url}/functions/v1/bird-sms`,{method:"POST",headers:{Authorization:authHeader,apikey:anonKey,"Content-Type":"application/json"},body:JSON.stringify({phone:p.phone,message:text,category:"service"})}).catch(()=>null);if(sms?.ok)sent++;}return{attempted:profiles?.length??0,sent};};
 const disputeAliases=new Set(["dispute","disputed","open_dispute"]); if(disputeAliases.has(action)){const {data,error}=await supabase.rpc("open_dispute",{p_transaction_id:transactionId,p_reason:body.reason?.trim()||null,p_description:body.description?.trim()||null});if(error)return json({error:error.message},400);return json({success:true,transaction_id:transactionId,status:"disputed",dispute:data,sms_notifications:await notify("litige ouvert")});}
 const map:Record<string,string>={fund:"funded",funded:"funded",deliver:"delivered",delivered:"delivered",complete:"completed",completed:"completed",cancel:"cancelled",cancelled:"cancelled"};const toStatus=map[action];if(!toStatus)return json({error:"invalid_action"},400);
 const {error}=await supabase.rpc("transition_transaction",{p_transaction_id:transactionId,p_to_status:toStatus,p_reason:body.reason?.trim()||null});if(error)return json({error:error.message},400);
 return json({success:true,transaction_id:transactionId,status:toStatus,sms_notifications:await notify(toStatus)});
});
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
