"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/navigation/AppShell";
import { createClient } from "@/lib/supabase/client";

function ProfileIcon() { return <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" aria-hidden="true"><circle cx="12" cy="12" r="9.2"/><circle cx="12" cy="9" r="2.7"/><path d="M7.2 18c.9-2.6 2.5-3.9 4.8-3.9s3.9 1.3 4.8 3.9"/></svg>; }
function CheckIcon() { return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 12 4 4L19 6"/></svg>; }
function withTimeout<T>(promise: PromiseLike<T>, ms = 8000): Promise<T> { return Promise.race([Promise.resolve(promise), new Promise<T>((_, reject) => setTimeout(() => reject(new Error("Le chargement du profil prend trop de temps.")), ms))]); }

export default function ProfilePage() {
  const router = useRouter();
  const [profile, setProfile] = useState<any>(null); const [account, setAccount] = useState<any>(null); const [security, setSecurity] = useState<any>(null); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");

  useEffect(() => { let mounted = true; const load = async () => { try { const supabase = createClient(); const { data: { user }, error: authError } = await withTimeout(supabase.auth.getUser()); if (authError || !user) throw new Error("Session expirée. Reconnectez-vous."); const [profileResult, accountResult, securityResult] = await Promise.allSettled([withTimeout(supabase.rpc("get_my_profile")), withTimeout(supabase.rpc("get_my_account")), withTimeout(supabase.from("user_security").select("biometric_enabled").eq("user_id", user.id).maybeSingle())]); if (!mounted) return; if (profileResult.status === "fulfilled" && !profileResult.value.error) setProfile(profileResult.value.data); else setError("Impossible de charger les informations du profil."); if (accountResult.status === "fulfilled" && !accountResult.value.error) setAccount(accountResult.value.data); if (securityResult.status === "fulfilled" && !securityResult.value.error) setSecurity(securityResult.value.data); } catch (err) { if (mounted) setError(err instanceof Error ? err.message : "Impossible de charger le profil SafePay."); } finally { if (mounted) setLoading(false); } }; load(); return () => { mounted = false; }; }, []);

  async function uploadAvatar(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; if (!file.type.startsWith("image/")) { setError("Sélectionnez une image."); return; } if (file.size > 5 * 1024 * 1024) { setError("La photo doit faire 5 Mo maximum."); return; } setError(""); setUploading(true); try { const supabase = createClient(); const { data: { user } } = await withTimeout(supabase.auth.getUser()); if (!user) throw new Error("Session expirée."); const ext = file.name.split(".").pop()?.toLowerCase() || "jpg"; const path = `${user.id}/avatar.${ext}`; const { error: uploadError } = await withTimeout(supabase.storage.from("avatars").upload(path, file, { upsert: true, contentType: file.type, cacheControl: "3600" })); if (uploadError) throw uploadError; const { data: publicData } = supabase.storage.from("avatars").getPublicUrl(path); const avatarUrl = `${publicData.publicUrl}?v=${Date.now()}`; const { error: updateError } = await withTimeout(supabase.from("profiles").update({ avatar_url: avatarUrl }).eq("id", user.id)); if (updateError) throw updateError; const { data: updatedProfile } = await withTimeout(supabase.rpc("get_my_profile")); setProfile(Array.isArray(updatedProfile) ? updatedProfile[0] : updatedProfile); window.dispatchEvent(new CustomEvent("safepay-avatar-updated", { detail: { url: avatarUrl } })); } catch (err) { setError(err instanceof Error ? err.message : "Impossible de modifier la photo de profil."); } finally { setUploading(false); } }
  async function logout() { try { sessionStorage.removeItem("safepay-profile-complete"); } catch {} const supabase = createClient(); await supabase.auth.signOut(); router.replace("/"); }

  const normalizedProfile = Array.isArray(profile) ? profile[0] : profile;
  const fullName = normalizedProfile?.full_name || account?.name || "Utilisateur SafePay"; const phone = normalizedProfile?.phone || account?.phone || "Non renseigné"; const country = normalizedProfile?.country || account?.country || "Non renseigné"; const role = normalizedProfile?.role === "seller" ? "Vendeur" : normalizedProfile?.role === "admin" ? "Administrateur" : "Client"; const avatarUrl = normalizedProfile?.avatar_url || "";

  return <AppShell><section className="sp-page"><div className="sp-page-head"><div><p className="sp-eyebrow">Compte</p><h1 className="sp-title">Profil</h1></div></div>
    {loading ? <div className="sp-page-loading"><span className="sp-loader"/>Chargement du profil…</div> : <>
      <section className="sp-section-card sp-profile-card"><label className="sp-avatar-upload" title="Changer la photo de profil"><div className="sp-avatar-frame">{avatarUrl ? <img src={avatarUrl} alt="Photo de profil" onError={() => setProfile((p: any) => p ? { ...(Array.isArray(p) ? p[0] : p), avatar_url: "" } : p)}/> : <ProfileIcon />}</div><input type="file" accept="image/*" onChange={uploadAvatar} disabled={uploading}/><span>{uploading ? "Envoi…" : "Modifier la photo"}</span></label><h2>{fullName}</h2><p className="sp-muted">{role}</p></section>
      <section className="sp-section-card"><div className="sp-section-head"><h2>Informations personnelles</h2></div><div className="sp-detail-grid"><div><span>Téléphone</span><strong>{phone}</strong></div><div><span>Pays</span><strong>{country}</strong></div><div><span>Rôle</span><strong>{role}</strong></div></div></section>
      <section className="sp-section-card"><div className="sp-section-head"><h2>Vérification</h2></div><div style={{display:"grid",gap:10,marginTop:10}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><span style={{fontSize:12}}>Téléphone</span>{normalizedProfile?.phone_verified?<span className="sp-success-note"><CheckIcon/> Vérifié</span>:<span className="sp-muted">Non vérifié</span>}</div></div></section>
      <section className="sp-section-card"><div className="sp-section-head"><h2>Sécurité</h2></div><div style={{display:"grid",gap:10,marginTop:10}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><span style={{fontSize:12}}>PIN</span><span className="sp-success-note">Protégé</span></div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><span style={{fontSize:12}}>Biométrie</span><span className="sp-muted">{security?.biometric_enabled?"Activée":"Désactivée"}</span></div></div><button className="sp-secondary-button" style={{marginTop:12}} onClick={()=>router.push("/settings")}>Gérer la sécurité</button></section>
      <section className="sp-section-card"><div className="sp-action-stack"><button className="sp-secondary-button" onClick={()=>router.push("/notifications")}>Notifications</button><button className="sp-secondary-button" onClick={()=>router.push("/support")}>Support</button><button className="sp-secondary-button" onClick={()=>router.push("/feedback")}>Donner mon avis</button><button className="sp-secondary-button" onClick={()=>router.push("/settings")}>Paramètres</button><button className="safepay-primary sp-submit" onClick={logout}>Se déconnecter</button></div></section>
    </>}
    {error&&<p className="sp-error" role="alert">{error}</p>}
  </section></AppShell>;
}
