"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/navigation/AppShell";
import { createClient } from "@/lib/supabase/client";
import { getDisplayCurrency, getLanguage, getNotificationSoundEnabled, getTheme, setDisplayCurrency, setLanguage, setNotificationSoundEnabled, setTheme, type SafePayDisplayCurrency, type SafePayLanguage, type SafePayTheme } from "@/lib/preferences";
import { primeNotificationSound } from "@/lib/notificationSound";
import { useSafePayLanguage } from "@/lib/i18n";

function Icon({type}:{type:"theme"|"language"|"currency"|"pin"|"bio"}){const p={viewBox:"0 0 24 24",width:20,height:20,fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};if(type==="theme")return <svg {...p}><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>;if(type==="language")return <svg {...p}><path d="M4 5h8M8 3v2M6 5c.5 4 2.2 6.4 5 8M4.5 13c2.8-1.4 5-3.5 6.5-6M14 14h6M17 10l-3 9M15 17h5"/></svg>;if(type==="currency")return <svg {...p}><circle cx="12" cy="12" r="9"/><path d="M14.5 8.5c-.7-.7-1.7-1-2.8-1-1.7 0-2.7.9-2.7 2s1 1.7 2.8 2c1.9.3 2.8 1 2.8 2.3s-1.1 2.2-2.9 2.2c-1.1 0-2.1-.4-2.9-1.1M12 6v12"/></svg>;if(type==="pin")return <svg {...p}><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>;return <svg {...p}><path d="M12 11a2 2 0 0 1 2 2v2.5M9.5 18.5A7 7 0 0 0 12 6a6 6 0 0 0-5.7 4.2M16.5 18.5A10 10 0 0 0 12 4a9 9 0 0 0-8.4 5.7M7 21a10 10 0 0 0 5-1.3M18.5 21a13 13 0 0 0 1.5-6.1A8 8 0 0 0 4.8 12"/></svg>}

export default function SettingsPage(){
 const {language}=useSafePayLanguage(); const en=language==="en";
 const [theme,setThemeState]=useState<SafePayTheme>("system"); const [languageState,setLanguageState]=useState<SafePayLanguage>("fr"); const [currency,setCurrencyState]=useState<SafePayDisplayCurrency>("XOF"); const [sound,setSound]=useState(true); const [biometric,setBiometric]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [pinOpen,setPinOpen]=useState(false); const [currentPin,setCurrentPin]=useState(""); const [newPin,setNewPin]=useState(""); const [confirmPin,setConfirmPin]=useState("");
 useEffect(()=>{setThemeState(getTheme());setLanguageState(getLanguage());setCurrencyState(getDisplayCurrency());setSound(getNotificationSoundEnabled());const supabase=createClient();void (async()=>{const {data}=await supabase.rpc("get_my_security");if(data?.biometric_enabled!==undefined)setBiometric(Boolean(data.biometric_enabled));try{const {data:passkeys}=await supabase.auth.passkey.list();if(Array.isArray(passkeys)&&passkeys.length>0)setBiometric(true);}catch{}})();},[]);
 const changeTheme=(v:SafePayTheme)=>{setThemeState(v);setTheme(v)}; const changeLanguage=(v:SafePayLanguage)=>{setLanguageState(v);setLanguage(v)}; const changeCurrency=(v:SafePayDisplayCurrency)=>{setCurrencyState(v);setDisplayCurrency(v)};
 async function changeSound(v:boolean){setSound(v);setNotificationSoundEnabled(v);if(v){try{await primeNotificationSound()}catch{}}}
 async function toggleBiometric(){setBusy(true);setError("");setMessage("");try{const supabase=createClient();if(!biometric){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error(en?"Session expired.":"Session expirée.");if(!window.isSecureContext||!("PublicKeyCredential"in window))throw new Error(en?"This device/browser does not support passkeys.":"Cet appareil ou navigateur ne prend pas en charge les passkeys.");const {data,error:e}=await supabase.auth.registerPasskey();if(e)throw e;const {error:se}=await supabase.rpc("set_my_biometric",{p_enabled:true});if(se)throw se;setBiometric(true);setMessage(en?"Biometrics enabled. Your device passkey is registered with SafePay.":"Biométrie activée. La passkey de votre appareil est enregistrée avec SafePay.");}else{const {data:passkeys,error:e}=await supabase.auth.passkey.list();if(e)throw e;for(const passkey of passkeys??[]){const {error:de}=await supabase.auth.passkey.delete({passkeyId:passkey.id});if(de)throw de;}const {error:se}=await supabase.rpc("set_my_biometric",{p_enabled:false});if(se)throw se;setBiometric(false);setMessage(en?"Biometrics disabled.":"Biométrie désactivée.");}}catch(e){setError(e instanceof Error?e.message:(en?"Unable to change biometric security.":"Impossible de modifier la sécurité biométrique."));}finally{setBusy(false)}}
 async function savePin(){setError("");setMessage("");if(!/^\d{4,6}$/.test(newPin))return setError(en?"PIN must contain 4 to 6 digits.":"Le PIN doit contenir 4 à 6 chiffres.");if(newPin!==confirmPin)return setError(en?"The new PINs do not match.":"Les deux nouveaux PIN ne correspondent pas.");setBusy(true);try{const supabase=createClient();if(currentPin){const {data,error:e}=await supabase.rpc("verify_my_pin",{p_pin:currentPin});if(e)throw e;if(!data)throw new Error(en?"Current PIN is incorrect.":"Le PIN actuel est incorrect.")}const {error:e}=await supabase.rpc("set_my_pin",{p_pin:newPin});if(e)throw e;setMessage(en?"SafePay PIN updated.":"PIN SafePay mis à jour.");setPinOpen(false);setCurrentPin("");setNewPin("");setConfirmPin("");}catch(e){setError(e instanceof Error?e.message:(en?"Unable to change PIN.":"Impossible de modifier le PIN."));}finally{setBusy(false)}}
 return <AppShell><section className="sp-page"><div className="sp-page-head"><div><p className="sp-eyebrow">{en?"Preferences":"Préférences"}</p><h1 className="sp-title">{en?"Settings":"Paramètres"}</h1></div></div>
 <section className="sp-section-card"><h2>{en?"Appearance":"Apparence"}</h2><div className="settings-option"><span className="settings-option-icon blue"><Icon type="theme"/></span><span className="settings-option-main"><strong>{en?"Theme":"Thème"}</strong><small>{en?"System, Light or Dark":"Système, Clair ou Sombre"}</small></span></div><div className="settings-segment"><button className={theme==="system"?"active":""} onClick={()=>changeTheme("system")}>⚙️ {en?"System":"Système"}</button><button className={theme==="light"?"active":""} onClick={()=>changeTheme("light")}>☀️ {en?"Light":"Clair"}</button><button className={theme==="dark"?"active":""} onClick={()=>changeTheme("dark")}>🌙 {en?"Dark":"Sombre"}</button></div></section>
 <section className="sp-section-card"><h2>{en?"Language":"Langue"}</h2><div className="settings-option"><span className="settings-option-icon green"><Icon type="language"/></span><span className="settings-option-main"><strong>{en?"Application language":"Langue de l'application"}</strong></span><span className="settings-option-value">{languageState==="fr"?"Français":"English"}</span></div><div className="settings-segment"><button className={languageState==="fr"?"active":""} onClick={()=>changeLanguage("fr")}>🇫🇷 Français</button><button className={languageState==="en"?"active":""} onClick={()=>changeLanguage("en")}>🇬🇧 English</button></div></section>
 <section className="sp-section-card"><h2>{en?"Display currency":"Devise d'affichage"}</h2><div className="settings-option"><span className="settings-option-icon violet"><Icon type="currency"/></span><span className="settings-option-main"><strong>{en?"Preferred currency":"Devise préférée"}</strong><small>{en?"Display only; real balances remain XOF.":"Affichage uniquement ; les soldes réels restent en XOF."}</small></span><span className="settings-option-value">{currency}</span></div><select className="settings-select" value={currency} onChange={e=>changeCurrency(e.target.value as SafePayDisplayCurrency)}><option value="XOF">XOF — {en?"CFA Franc":"Franc CFA"}</option><option value="EUR">EUR — Euro</option><option value="USD">USD — {en?"US Dollar":"Dollar américain"}</option></select></section>
 <section className="sp-section-card"><h2>{en?"Security":"Sécurité"}</h2><button className="settings-option" onClick={()=>{setPinOpen(true);setError("")}}><span className="settings-option-icon orange"><Icon type="pin"/></span><span className="settings-option-main"><strong>SafePay PIN</strong><small>{en?"Create or change your secure code.":"Créer ou changer votre code secret sécurisé."}</small></span><span className="settings-option-value">{en?"Change":"Modifier"}</span></button><button className="settings-option" onClick={()=>void toggleBiometric()} disabled={busy} style={{marginTop:10}}><span className="settings-option-icon green"><Icon type="bio"/></span><span className="settings-option-main"><strong>{en?"Biometrics":"Biométrie"}</strong><small>{en?"Passkey protected by device biometrics or device PIN.":"Passkey protégée par la biométrie ou le PIN de votre appareil."}</small></span><span className={biometric?"settings-toggle active":"settings-toggle"}/></button></section>
 <section className="sp-section-card"><h2>{en?"Notifications":"Notifications"}</h2><button className="settings-option" onClick={()=>void changeSound(!sound)}><span className="settings-option-main"><strong>{en?"Notification sound":"Son des notifications"}</strong><small>{en?"Play a sound for SafePay notifications.":"Jouer un son pour les notifications SafePay."}</small></span><span className={sound?"settings-toggle active":"settings-toggle"}/></button></section>
 {message&&<p className="sp-success-note" role="status">{message}</p>}{error&&<p className="sp-error" role="alert">{error}</p>}
 {pinOpen&&<div className="sp-modal-backdrop" role="dialog" aria-modal="true"><div className="sp-modal"><button className="sp-modal-close" onClick={()=>setPinOpen(false)} aria-label={en?"Close":"Fermer"}>×</button><h2>{en?"Change SafePay PIN":"Changer le PIN SafePay"}</h2><input className="settings-input" type="password" inputMode="numeric" maxLength={6} placeholder={en?"Current PIN":"PIN actuel"} value={currentPin} onChange={e=>setCurrentPin(e.target.value)}/><input className="settings-input" type="password" inputMode="numeric" maxLength={6} placeholder={en?"New PIN":"Nouveau PIN"} value={newPin} onChange={e=>setNewPin(e.target.value)}/><input className="settings-input" type="password" inputMode="numeric" maxLength={6} placeholder={en?"Confirm PIN":"Confirmer le PIN"} value={confirmPin} onChange={e=>setConfirmPin(e.target.value)}/><button className="safepay-primary sp-submit" disabled={busy} onClick={()=>void savePin()}>{busy?(en?"Saving…":"Enregistrement…"):(en?"Save PIN":"Enregistrer le PIN")}</button></div></div>}
 </section></AppShell>;
}
